import axios from "axios";

const getAuthState = async () => {
  //TODO: handle possible errors. What could be possible errors?
  const response = await axios.get("http://localhost:8080/api/me", {
    withCredentials: true,
  });
  console.log(response.data);
  return {
    isLoggedIn: response.data.isLoggedIn,
    userStatus: response.data.userStatus,
  };
};

export default getAuthState;
